name: Cloud URL Shortener CI/CD

on:
  push:
    branches:
      - main
  
permissions:
  contents: read

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name cloudurlshortacr

      - name: Install kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: v0.2.19

      - name: Build backend image
        run: |
          docker build \
            -t cloudurlshortacr.azurecr.io/url-shortener-api:${{ github.sha }} \
            ./backend

      - name: Push backend image
        run: |
          docker push \
            cloudurlshortacr.azurecr.io/url-shortener-api:${{ github.sha }}

      - name: Build frontend image
        run: |
          docker build \
            -t cloudurlshortacr.azurecr.io/url-shortener-frontend:${{ github.sha }} \
            ./frontend

      - name: Push frontend image
        run: |
          docker push \
            cloudurlshortacr.azurecr.io/url-shortener-frontend:${{ github.sha }}

      - name: Azure Kubernetes Service login
        uses: azure/aks-set-context@v4
        with:
          cluster-name: cloud-url-shortener-aks
          resource-group: cloud-url-shortener-dev-rg
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          use-kubelogin: true

      - name: Deploy to AKS
        run: |
          kubectl apply -f kubernetes/